#!/usr/bin/env python3
"""Install the TRELLIS Mac runtime into <data-dir>/runtimes/trellis.

Layout (mirrors trellis-mac so its patch script works unmodified):
  runtimes/trellis/trellis-mac/        @ pinned SHA (MIT, see NOTICE)
    TRELLIS.2/                         @ pinned SHA (upstream microsoft)
    deps/{utils3d,mtlbvh,mtldiffrast,mtlmesh,mtlgemm,trellis2-apple}
    stubs/  (generated by patches/mps_compat.py)

Python packages (utils3d, Metal exts) go into venvs/trellis.
Idempotent: marker files skip finished steps. `--reinstall` resets.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

TRELLIS_MAC_PIN = "d58628f4f5b9c3de8274cb110074154f4b31cef2"
TRELLIS2_PIN = "75fbf0183001ed9876c8dbb35de6b68552ee08bd"
UTIL3D_PIN = "9a4eb15e4021b67b12c460c7057d642626897ec8"
NOTICE = """trellis-mac (https://github.com/shivampkumar/trellis-mac) MIT (c) 2026.
Vendored/cloned at pinned revision for 3DFM's TRELLIS-on-MPS runtime;
patches/backends originate there. Metal extensions: pedronaugusto forks.
Upstream TRELLIS.2: microsoft (MIT).
"""


def run(cmd, env=None, cwd=None):
    e = dict(os.environ)
    if env:
        e.update(env)
    print("+", " ".join(str(c) for c in cmd), flush=True)
    subprocess.run(cmd, env=e, cwd=cwd, check=True)


def clone(url: str, dest: Path, pin: str | None, shallow_ok=True):
    if (dest / ".git").exists():
        print(f"skip clone {dest.name} (present)")
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    if pin and not shallow_ok:
        run(["git", "clone", url, str(dest)])
        run(["git", "-C", str(dest), "checkout", pin])
    else:
        run(["git", "clone", "--depth", "1", url, str(dest)])
        if pin:
            try:
                run(["git", "-C", str(dest), "fetch", "--depth", "1",
                     "origin", pin])
                run(["git", "-C", str(dest), "checkout", pin])
            except subprocess.CalledProcessError:
                print(f"warn: pin {pin} not fetchable; using HEAD")


def _uv() -> str:
    import shutil
    for c in ("uv", os.path.expanduser("~/.local/bin/uv"),
              "/opt/homebrew/bin/uv"):
        if c == "uv":
            if shutil.which("uv"):
                return "uv"
        elif os.path.exists(c):
            return c
    raise RuntimeError("uv not found")


def upip(venv_py: Path, *args, extra_env=None):
    run([_uv(), "pip", "install", "--python", str(venv_py), *args],
        env=extra_env)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", required=True)
    ap.add_argument("--reinstall", action="store_true")
    ap.add_argument("--skip-metal", action="store_true")
    ap.add_argument("--venv", default="trellis",
                    help="target venv under <data-dir>/venvs (default trellis)")
    ns = ap.parse_args()

    data = Path(ns.data_dir).expanduser()
    rt = data / "runtimes" / "trellis"
    tm = rt / "trellis-mac"
    venv_py = data / "venvs" / ns.venv / "bin" / "python"
    if not venv_py.exists():
        print(f"{ns.venv} venv missing; create it first",
              file=sys.stderr)
        return 1
    if ns.reinstall:
        import shutil
        shutil.rmtree(rt, ignore_errors=True)
    rt.mkdir(parents=True, exist_ok=True)
    (rt / "NOTICE").write_text(NOTICE)

    # -- code ----------------------------------------------------------
    clone("https://github.com/shivampkumar/trellis-mac.git", tm,
          TRELLIS_MAC_PIN)
    clone("https://github.com/microsoft/TRELLIS.2.git", tm / "TRELLIS.2",
          TRELLIS2_PIN)
    deps = tm / "deps"
    clone("https://github.com/EasternJournalist/utils3d.git",
          deps / "utils3d", UTIL3D_PIN, shallow_ok=False)
    metal_repos = {
        "mtlbvh": "https://github.com/pedronaugusto/mtlbvh.git",
        "mtldiffrast": "https://github.com/pedronaugusto/mtldiffrast.git",
        "mtlmesh": "https://github.com/pedronaugusto/mtlmesh.git",
        "mtlgemm": "https://github.com/pedronaugusto/mtlgemm.git",
        "trellis2-apple": "https://github.com/pedronaugusto/trellis2-apple.git",
    }
    for name, url in metal_repos.items():
        clone(url, deps / name, None)

    # -- python deps ----------------------------------------------------
    upip(venv_py, str(deps / "utils3d"))

    metal_ok = False
    skip_marker = tm / ".skip-metal"
    use_metal = True
    if ns.skip_metal:
        skip_marker.write_text("requested\n")
        use_metal = False
    elif skip_marker.exists() and skip_marker.read_text().strip() == "requested":
        use_metal = False
    if use_metal:
        # honor Xcode.app via DEVELOPER_DIR if set by caller
        has_tc = subprocess.run(
            ["xcrun", "-sdk", "macosx", "metal", "--version"],
            capture_output=True).returncode == 0
        if not has_tc:
            print("metal toolchain missing -> KDTree fallback "
                  "(recorded, setup continues)")
            skip_marker.write_text("no-toolchain\n")
            use_metal = False
        elif skip_marker.exists():
            skip_marker.unlink(missing_ok=True)
    if use_metal:
        import shutil as _sh
        _brew = _sh.which("brew")
        _eigen = ""
        if _brew:
            import subprocess as _sp
            try:
                _eigen = _sp.run([_brew, "--prefix", "eigen"],
                                 capture_output=True, text=True,
                                 timeout=15).stdout.strip() + "/include/eigen3"
            except Exception:
                _eigen = ""
        if not _eigen or not os.path.isdir(_eigen):
            for cand in ("/opt/homebrew/include/eigen3",
                         "/usr/local/include/eigen3"):
                if os.path.isdir(cand):
                    _eigen = cand
                    break
        menv = {
            "MACOSX_DEPLOYMENT_TARGET": "12.0",
            "CPATH": ":".join(filter(None, [_eigen,
                                            "/opt/homebrew/include",
                                            os.environ.get("CPATH", "")])),
            "CFLAGS": "-mmacosx-version-min=12.0 "
                      "-Wno-error=unguarded-availability-new",
            "CXXFLAGS": "-mmacosx-version-min=12.0 "
                        "-Wno-error=unguarded-availability-new",
            "LDFLAGS": "-mmacosx-version-min=12.0",
        }
        upip(venv_py, "setuptools", "wheel", "pybind11")
        for pkg in ("mtlbvh", "mtldiffrast", "mtlmesh", "mtlgemm"):
            try:
                upip(venv_py, "--no-build-isolation", str(deps / pkg),
                     extra_env=menv)
            except subprocess.CalledProcessError:
                print(f"warn: {pkg} build failed; continuing")
        try:
            upip(venv_py, "--no-build-isolation",
                 str(deps / "trellis2-apple" / "o-voxel"), extra_env=menv)
        except subprocess.CalledProcessError:
            print("warn: o-voxel apple fork failed; KDTree fallback")
    # probe what actually imported
    # NOTE: repo dir != import name (mtlgemm->flex_gemm, mtlmesh->cumesh)
    probe = ("import importlib.util as u;"
             "mods=['flex_gemm','mtldiffrast','mtlbvh','cumesh','o_voxel',"
             "'fast_simplification','xatlas'];"
             "print({m: bool(u.find_spec(m)) for m in mods})")
    r = subprocess.run([str(venv_py), "-c", probe], capture_output=True,
                       text=True)
    print("import probe:", r.stdout.strip() or r.stderr.strip()[-500:])
    metal_ok = use_metal and "'flex_gemm': True" in r.stdout \
        and "'o_voxel': True" in r.stdout

    # -- patches ----------------------------------------------------------
    run([str(venv_py), str(tm / "patches" / "mps_compat.py")], cwd=str(tm))

    (rt / "manifest.json").write_text(json.dumps({
        "trellis_mac_pin": TRELLIS_MAC_PIN,
        "trellis2_pin": TRELLIS2_PIN,
        "utils3d_pin": UTIL3D_PIN,
        "metal": bool(metal_ok),
    }, indent=2))
    print(f"trellis runtime ready (metal={metal_ok})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
